import { RequestHandler } from "express";
import { createClient } from "@supabase/supabase-js";

const SUPABASE_URL = process.env.VITE_SUPABASE_URL;
const SUPABASE_SERVICE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

function getSupabaseAdmin() {
  if (!SUPABASE_URL || !SUPABASE_SERVICE_KEY) {
    throw new Error("Supabase config missing");
  }
  return createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY);
}

function generatePackageJson(projectName: string): string {
  return JSON.stringify({
    name: projectName.toLowerCase().replace(/[^a-z0-9]/g, "-"),
    version: "1.0.0",
    main: "index.js",
    scripts: {
      start: "expo start",
      android: "expo start --android",
      ios: "expo start --ios",
      web: "expo start --web",
    },
    dependencies: {
      expo: "~51.0.0",
      "expo-status-bar": "~1.12.1",
      react: "18.2.0",
      "react-native": "0.74.5",
      "@react-navigation/native": "^6.1.18",
      "@react-navigation/native-stack": "^6.11.0",
      "react-native-screens": "~3.31.1",
      "react-native-safe-area-context": "4.10.5",
    },
    devDependencies: {
      "@babel/core": "^7.20.0",
      typescript: "~5.3.3",
      "@types/react": "~18.2.45",
    },
    private: true,
  }, null, 2);
}

function generateAppTsx(screens: string[]): string {
  const imports = screens.map(
    (s) => `import ${s}Screen from "./screens/${s}Screen";`
  ).join("\n");

  const stackScreens = screens.map(
    (s) => `        <Stack.Screen name="${s}" component={${s}Screen} />`
  ).join("\n");

  return `import { NavigationContainer } from "@react-navigation/native";
import { createNativeStackNavigator } from "@react-navigation/native-stack";
import { StatusBar } from "expo-status-bar";
${imports}

const Stack = createNativeStackNavigator();

export default function App() {
  return (
    <NavigationContainer>
      <StatusBar style="auto" />
      <Stack.Navigator initialRouteName="${screens[0] || "Home"}">
${stackScreens}
      </Stack.Navigator>
    </NavigationContainer>
  );
}
`;
}

function generateScreen(name: string): string {
  return `import { View, Text, StyleSheet, ScrollView, TouchableOpacity } from "react-native";

export default function ${name}Screen({ navigation }: any) {
  return (
    <ScrollView style={styles.container}>
      <View style={styles.content}>
        <Text style={styles.title}>${name}</Text>
        <Text style={styles.subtitle}>This screen was generated by Morphic</Text>
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#ffffff",
  },
  content: {
    flex: 1,
    padding: 24,
    paddingTop: 60,
  },
  title: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#1a1a1a",
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 16,
    color: "#666666",
  },
});
`;
}

function generateTsConfig(): string {
  return JSON.stringify({
    extends: "expo/tsconfig.base",
    compilerOptions: {
      strict: true,
    },
  }, null, 2);
}

function generateAppJson(projectName: string): string {
  const slug = projectName.toLowerCase().replace(/[^a-z0-9]/g, "-");
  return JSON.stringify({
    expo: {
      name: projectName,
      slug,
      version: "1.0.0",
      orientation: "portrait",
      icon: "./assets/icon.png",
      userInterfaceStyle: "light",
      splash: {
        backgroundColor: "#ffffff",
      },
      ios: { supportsTablet: true },
      android: { adaptiveIcon: { backgroundColor: "#ffffff" } },
      web: { favicon: "./assets/favicon.png" },
    },
  }, null, 2);
}

export const handleExport: RequestHandler = async (req, res) => {
  try {
    const { projectId, userId } = req.body;

    if (!projectId || !userId) {
      res.status(400).json({ error: "Missing projectId or userId" });
      return;
    }

    const supabase = getSupabaseAdmin();

    const { data: project } = await supabase
      .from("projects")
      .select("*")
      .eq("id", projectId)
      .eq("user_id", userId)
      .single();

    if (!project) {
      res.status(404).json({ error: "Project not found" });
      return;
    }

    const { data: generatedFiles } = await supabase
      .from("generated_files")
      .select("file_path, file_type, content")
      .eq("project_id", projectId);

    const screens = ["Home", "Login", "Dashboard", "Settings", "Profile"];

    const files: Record<string, string> = {
      "package.json": generatePackageJson(project.name),
      "tsconfig.json": generateTsConfig(),
      "app.json": generateAppJson(project.name),
      "App.tsx": generateAppTsx(screens),
    };

    for (const screen of screens) {
      files[`screens/${screen}Screen.tsx`] = generateScreen(screen);
    }

    if (generatedFiles && generatedFiles.length > 0) {
      for (const gf of generatedFiles) {
        if (gf.content) {
          files[gf.file_path] = gf.content;
        }
      }
    }

    files["README.md"] = `# ${project.name}

Generated by Morphic - AI Web to Mobile Conversion

## Getting Started

\`\`\`bash
npm install
npx expo start
\`\`\`

## Structure

- \`App.tsx\` - Main app entry with navigation
- \`screens/\` - App screens
- \`components/\` - Reusable components
- \`services/\` - API services
`;

    await supabase.from("logs").insert({
      user_id: userId,
      project_id: projectId,
      action: "export",
      level: "info",
      message: `Exported project "${project.name}" with ${Object.keys(files).length} files`,
    });

    res.json({
      success: true,
      projectName: project.name,
      files,
      fileCount: Object.keys(files).length,
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Export failed";
    res.status(500).json({ error: message });
  }
};
